version: '2'

networks:
  graph:
    external: true

services:
  # ----------------------------------------
  # DataStax Enterprise
  # ----------------------------------------
  dse:
    image: datastax/dse-server:6.8.10
    command: [ -g ]
    ports:
      - "9042:9042"
      - "8983:8983"
      - "8182:8182"
      - "8183:8183"
    environment:
      - DS_LICENSE=accept
      - DC=DC1
      - JVM_EXTRA_OPTS=-Xmx1g -Xms1g
      - NUM_TOKENS=32
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    networks:
      - graph
    # Specify the container name explicitly to avoid getting underscores (see note above)
    container_name: dse
    
  # ----------------------------------------
  # DataStax Studio
  # ----------------------------------------
  studio:
     image: datastax/dse-studio:6.8.9
     ports:
       - "9091:9091"
     depends_on:
       - dse
     environment:
       DS_LICENSE: accept
      #  for windows users - start studio image without volumes (remove the below 2 lines)
     volumes:
       - "./datastax-studio-config:/var/lib/datastax-studio"
     networks:
       - graph